pipeline:
  name: WeatherApp
  identifier: WeatherApp
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: WeatherApp
        repoName: Weather-Forecast
        build: <+input>
  stages:
    - stage:
        name: Build-Weather-App
        identifier: BuildWeatherApp
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      ls -la



                      pwd
