pipeline:
  name: WeatherApp
  identifier: WeatherApp
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: WeatherApp
        repoName: Weather-Forecast
        build: <+input>
  stages:
    - stage:
        name: Build-Weather-App
        identifier: BuildWeatherApp
        template:
          templateRef: default
          versionLabel: "1"
